### ISSUE TITLE
Plan to support Prisma and user authentication?

### ISSUE THREAD

**Issue by 2peter3** [mhaidarhanif/rewinds-legacy#1]
Hey, are there any plans of adding Prisma with user register/login/profile?

Thank you :)

**Comment by mhaidarhanif** [comment]
Hey @2peter3 thanks for asking.

For database and Prisma-related practices, check out the official Remix Stacks instead here: https://remix.run/stacks

Because this starter kit is only intended for styling purposes with Tailwind, not the whole full stack situation. There will be no database in this repo.
